# Pre-commit hooks configuration
# Install: pip install pre-commit && pre-commit install

repos:
  # Auto-generate talks index from metadata (Go binaries)
  - repo: local
    hooks:
      - id: generate-talks-index
        name: Generate Talks Index
        entry: bin/generate-index
        language: system
        files: '(metadata\.yaml|README.*\.md)$'
        pass_filenames: false
        always_run: false

      - id: check-metadata
        name: Check Talk Metadata
        entry: bin/check-metadata
        language: system
        files: '^[0-9]{4}/.*'
        pass_filenames: false
        always_run: false

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: mixed-line-ending

  # Markdown linting (optional) - commented out due to Ruby version requirement
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.12.0
  #   hooks:
  #     - id: markdownlint
  #       args: ['--fix']
